import type { SearchOrder, SearchProduct, SearchWholesaler } from "./types";

/**
 * 통합 검색이 훑는 더미. API가 붙으면 이 파일만 지운다.
 *
 * **`features/catalog`의 상품 더미와 같은 것을 다시 적는다.** feature끼리는
 * 직접 import 하지 않는다(ESLint가 막는다) — 검색과 목록은 서버가 붙으면 서로
 * 다른 엔드포인트를 부를 자리라 지금 한쪽에 묶어 두면 나중에 뜯어야 한다.
 * 대신 **id와 품번은 같은 값**이어야 `상품 보기`가 실제 상세로 간다.
 *
 * 표로 적는 이유: 목록 쪽 더미와 어긋났는지를 눈으로 대조할 수 있어야 해서다.
 * 객체로 펼치면 19줄이 190줄이 되고 그 순간 아무도 두 파일을 맞춰 보지 않는다.
 */
type Row = [
  id: string,
  code: string,
  name: string,
  wholesalerId: string,
  wholesalerName: string,
  colorCount: number,
  sizeLabel: string,
  priceMin: number,
  hasRange: boolean,
];

const ROWS: readonly Row[] = [
  [
    "p-flower-shirt",
    "SU-18",
    "빈티지 플라워 셔츠",
    "w-moodon",
    "무드온",
    3,
    "5",
    12500,
    true,
  ],
  [
    "p-wide-slacks",
    "SU-24",
    "링클프리 와이드 슬랙스",
    "w-basic",
    "더베이직",
    4,
    "4",
    14000,
    true,
  ],
  [
    "p-linen-jacket",
    "SU-31",
    "오버핏 린넨 자켓",
    "w-urban",
    "어반무드",
    2,
    "Free",
    24500,
    false,
  ],
  [
    "p-check-shirt",
    "SU-07",
    "체크무늬 셔츠",
    "w-moodon",
    "무드온",
    2,
    "5",
    30000,
    true,
  ],
  [
    "p-shirring-dress",
    "SU-42",
    "셔링 미니 원피스",
    "w-lavien",
    "라비앙",
    2,
    "2",
    16500,
    true,
  ],
  [
    "p-cotton-tee",
    "SU-03",
    "데일리 코튼 티셔츠",
    "w-cotton",
    "코튼클럽",
    5,
    "5",
    4500,
    true,
  ],
  [
    "p-highwaist-denim",
    "SU-15",
    "하이웨스트 데님 팬츠",
    "w-denim",
    "데님하우스",
    2,
    "3",
    18000,
    true,
  ],
  [
    "p-pleats-skirt",
    "SU-11",
    "플리츠 스커트",
    "w-moodon",
    "무드온",
    2,
    "4",
    7500,
    true,
  ],
  [
    "p-linen-blouse",
    "SU-51",
    "여름 린넨 블라우스",
    "w-moodon",
    "무드온",
    2,
    "4",
    16000,
    true,
  ],
  [
    "p-basic-tee",
    "SU-52",
    "기본 반팔 티셔츠",
    "w-moodon",
    "무드온",
    4,
    "4",
    8500,
    true,
  ],
  [
    "p-hood-zipup",
    "SU-53",
    "스트릿 후드 집업",
    "w-moodon",
    "무드온",
    3,
    "5",
    28000,
    true,
  ],
  [
    "p-daily-slacks",
    "SU-54",
    "데일리 슬랙스",
    "w-moodon",
    "무드온",
    2,
    "4",
    19000,
    true,
  ],
  [
    "p-kids-sweat",
    "SU-58",
    "키즈 맨투맨",
    "w-moodon",
    "무드온",
    3,
    "3",
    11000,
    true,
  ],
  [
    "p-canvas-tote",
    "SU-71",
    "캔버스 토트백",
    "w-urban",
    "어반무드",
    3,
    "Free",
    9000,
    false,
  ],
  [
    "p-strap-sandal",
    "SU-73",
    "스트랩 샌들",
    "w-lavien",
    "라비앙",
    2,
    "3",
    21000,
    true,
  ],
  [
    "p-leather-belt",
    "SU-77",
    "레더 벨트",
    "w-urban",
    "어반무드",
    3,
    "Free",
    6500,
    false,
  ],
  [
    "p-washed-denim-jacket",
    "SU-81",
    "워시드 데님 자켓",
    "w-denim",
    "데님하우스",
    2,
    "4",
    32000,
    true,
  ],
];

export const SEARCH_PRODUCTS: readonly SearchProduct[] = ROWS.map(
  ([
    id,
    code,
    name,
    wholesalerId,
    wholesalerName,
    colorCount,
    sizeLabel,
    priceMin,
    hasRange,
  ]) => ({
    id,
    code,
    name,
    wholesalerId,
    wholesalerName,
    colorCount,
    sizeLabel,
    priceMin,
    hasRange,
  }),
);

export const SEARCH_WHOLESALERS: readonly SearchWholesaler[] = [
  {
    id: "w-moodon",
    name: "무드온",
    initial: "무",
    location: "청평화패션몰 2층 24호",
  },
  {
    id: "w-basic",
    name: "더베이직",
    initial: "더",
    location: "APM 3층 12호",
  },
  {
    id: "w-urban",
    name: "어반무드",
    initial: "어",
    location: "디오트 4층 41호",
  },
  {
    id: "w-lavien",
    name: "라비앙",
    initial: "라",
    /* `3층 7호`가 아니다 — 확정 와이어프레임 `12_partners.html` 기준.
       사입하러 갈 자리를 말하는 화면이 서로 다른 주소를 대면 사장이 없는 자리를
       찾아 헤맨다(F2). 값은 feature마다 두되 **같은 값**이어야 한다 */
    location: "청평화패션몰 3층 8호",
  },
  {
    id: "w-cotton",
    name: "코튼클럽",
    initial: "코",
    location: "디오트 3층 51호",
  },
  {
    id: "w-denim",
    name: "데님하우스",
    initial: "데",
    /* `디오트 2층 18호`가 아니다 — 확정 와이어프레임 2장(`12_partners`·
       `09_order_detail`)이 `디오트 지하 1층 12호`로 일치한다(F2) */
    location: "디오트 지하 1층 12호",
  },
];

/** 전에 넣은 주문. 통합 주문 하나가 여러 도매처를 묶는다 */
export const SEARCH_ORDERS: readonly SearchOrder[] = [
  {
    id: "o-20260717-0088",
    orderNo: "20260717-1152-0088",
    orderedAt: "2026-07-17",
    productName: "체크무늬 셔츠",
    productCode: "SU-07",
    optionSummary: "블랙/M 5장 · 블랙/L 4장",
    wholesalerSummary: "무드온 외 1곳",
    totalSheets: 32,
    totalAmount: 417000,
    statusLabel: "확정 대기",
  },
  {
    id: "o-20260703-0041",
    orderNo: "20260703-2014-0041",
    orderedAt: "2026-07-03",
    productName: "데일리 코튼 티셔츠",
    productCode: "SU-03",
    optionSummary: "화이트/M 10장 · 화이트/L 10장",
    wholesalerSummary: "코튼클럽",
    totalSheets: 20,
    totalAmount: 94000,
    statusLabel: "수령 완료",
  },
  {
    id: "o-20260621-0012",
    orderNo: "20260621-2338-0012",
    orderedAt: "2026-06-21",
    productName: "빈티지 플라워 셔츠",
    productCode: "SU-18",
    optionSummary: "레드/S 6장 · 네이비/M 6장",
    wholesalerSummary: "무드온",
    totalSheets: 12,
    totalAmount: 154000,
    statusLabel: "부분 출고",
  },
];
