import type { CatalogProduct, Wholesaler } from "./types";

/**
 * 마켓 탐색 3화면(홈 · 도매처 홈 · 찜 목록)이 읽는 더미. API가 붙으면 이 파일만 지운다.
 *
 * 값은 확정 와이어프레임 `15_retail-hallmark/parts/00·03·04`의 카드 그대로 옮기되
 * 두 가지를 고쳤다.
 * - 품번은 도매 `SU-18` 형식이다(게이트 Q3). 와이어프레임의 `ST-002`는 더미 문자열이다.
 * - 컬러는 고정 팔레트 26종의 이름이다(게이트 Q4). 와이어프레임은 개수만 적어 뒀다.
 *
 * **재고 수치는 어디에도 없다**(게이트 Q1). 판매가능 수량을 소매에 줄지가 아직
 * 미결정이라, 숫자를 지어내지 않고 상품 상세의 `재고 소진 · 미송 가능` 배지로만 말한다.
 */

export const WHOLESALERS: readonly Wholesaler[] = [
  {
    id: "w-moodon",
    name: "무드온",
    initial: "무",
    location: "청평화패션몰 2층 24호",
    businessHours: "20:00~06:00",
    /* 누적 주문·진행 중은 여전히 더미다(§3-D·G에서 산식이 끊겨 있다). 다만
       **미결제 잔액과 마지막 입금은 더 이상 더미가 아니다** — `features/settlement`의
       거래 원장이 돈의 원본이 되면서 거기서 나온 값으로 맞췄다. 와이어프레임
       `03_wholesaler.html`은 마지막 입금을 2026.07.16이라 적었지만 원장과 어긋나므로
       원장을 따른다(01-pm.md §7-4). 값을 고칠 일이 생기면 원장을 먼저 고친다 */
    stats: {
      orderCount: 18,
      ongoingCount: 3,
      pendingCount: 1,
      backorderCount: 2,
      unpaidAmount: 589000,
      lastPaidAt: "2026-08-28",
    },
  },
  {
    id: "w-basic",
    name: "더베이직",
    initial: "더",
    location: "APM 3층 12호",
    businessHours: "20:00~05:00",
    /* **거래 이력이 없는 도매처다** — 거래처 목록(`/wholesalers`) 4곳에 안 든다.
       목록에 없는 곳이 미결제 잔액을 갖고 있으면 총 미수 859,000원이 어디서
       나왔는지 화면에서 설명되지 않는다. 마지막 입금은 없으므로 null이다 */
    stats: {
      orderCount: 0,
      ongoingCount: 0,
      pendingCount: 0,
      backorderCount: 0,
      unpaidAmount: 0,
      lastPaidAt: null,
    },
  },
  {
    id: "w-urban",
    name: "어반무드",
    initial: "어",
    location: "디오트 4층 41호",
    businessHours: "20:00~06:00",
    /* 더베이직과 같다 — 주문한 적 없는 도매처라 통계가 전부 0이다 */
    stats: {
      orderCount: 0,
      ongoingCount: 0,
      pendingCount: 0,
      backorderCount: 0,
      unpaidAmount: 0,
      lastPaidAt: null,
    },
  },
  {
    id: "w-lavien",
    name: "라비앙",
    initial: "라",
    /* `3층 7호`가 아니다 — 확정 와이어프레임 `12_partners.html` 기준 */
    location: "청평화패션몰 3층 8호",
    businessHours: "21:00~06:00",
    /* 미결제 잔액이 **음수**다. 350,000을 보냈는데 320,000만 주문에 배정돼
       30,000이 남았고, 화면에는 `선수금 30,000원`으로 나간다(§3-0 E) */
    stats: {
      orderCount: 5,
      ongoingCount: 1,
      pendingCount: 0,
      backorderCount: 1,
      unpaidAmount: -30000,
      lastPaidAt: "2026-08-02",
    },
  },
  {
    id: "w-cotton",
    name: "코튼클럽",
    initial: "코",
    location: "디오트 3층 51호",
    businessHours: "20:00~06:00",
    stats: {
      orderCount: 21,
      ongoingCount: 1,
      pendingCount: 0,
      backorderCount: 1,
      unpaidAmount: 90000,
      lastPaidAt: "2026-08-18",
    },
  },
  {
    id: "w-denim",
    name: "데님하우스",
    initial: "데",
    /* `디오트 2층 18호`가 아니다 — 확정 와이어프레임 2장(`12_partners`·
       `09_order_detail`)이 `디오트 지하 1층 12호`로 일치한다 */
    location: "디오트 지하 1층 12호",
    businessHours: "20:00~05:00",
    stats: {
      orderCount: 9,
      ongoingCount: 1,
      pendingCount: 0,
      backorderCount: 1,
      unpaidAmount: 180000,
      lastPaidAt: "2026-08-20",
    },
  },
];

/**
 * 마켓에 걸린 상품. **게시 내림(`UNPUBLISHED`)은 여기 없다** — 목록에서 빠지는 것이
 * 게시 내림의 정의라서다. 그 상태의 화면은 상품 상세(`features/product`)가 갖는다.
 */
export const CATALOG_PRODUCTS: readonly CatalogProduct[] = [
  {
    id: "p-flower-shirt",
    name: "빈티지 플라워 셔츠",
    code: "SU-18",
    wholesalerId: "w-moodon",
    wholesalerName: "무드온",
    categorySlug: "tops",
    colors: ["레드", "네이비", "카키"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    priceMin: 12500,
    priceMax: 13500,
    status: "ON_SALE",
    purchased: false,
    favorited: true,
    listedAt: "2026-08-28",
    favoritedAt: "2026-08-29",
  },
  {
    id: "p-wide-slacks",
    name: "링클프리 와이드 슬랙스",
    code: "SU-24",
    wholesalerId: "w-basic",
    wholesalerName: "더베이직",
    categorySlug: "bottoms",
    colors: ["블랙", "차콜", "베이지", "카키"],
    sizes: ["S", "M", "L", "XL"],
    priceMin: 14000,
    priceMax: 15200,
    status: "ON_SALE",
    purchased: false,
    favorited: false,
    listedAt: "2026-08-26",
    favoritedAt: null,
  },
  {
    id: "p-linen-jacket",
    name: "오버핏 린넨 자켓",
    code: "SU-31",
    wholesalerId: "w-urban",
    wholesalerName: "어반무드",
    categorySlug: "outer",
    colors: ["아이보리", "베이지"],
    sizes: ["Free"],
    priceMin: 24500,
    priceMax: 24500,
    status: "ON_SALE",
    purchased: false,
    favorited: false,
    listedAt: "2026-08-25",
    favoritedAt: null,
  },
  {
    id: "p-check-shirt",
    name: "체크무늬 셔츠",
    code: "SU-07",
    wholesalerId: "w-moodon",
    wholesalerName: "무드온",
    categorySlug: "tops",
    colors: ["블랙", "네이비"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    priceMin: 30000,
    priceMax: 31500,
    status: "ON_SALE",
    purchased: true,
    favorited: true,
    listedAt: "2026-08-24",
    favoritedAt: "2026-08-30",
  },
  {
    id: "p-shirring-dress",
    name: "셔링 미니 원피스",
    code: "SU-42",
    wholesalerId: "w-lavien",
    wholesalerName: "라비앙",
    categorySlug: "dress-set",
    colors: ["크림", "핑크"],
    sizes: ["S", "M"],
    priceMin: 16500,
    priceMax: 17500,
    status: "ON_SALE",
    purchased: false,
    favorited: true,
    listedAt: "2026-08-23",
    favoritedAt: "2026-08-22",
  },
  {
    id: "p-cotton-tee",
    name: "데일리 코튼 티셔츠",
    code: "SU-03",
    wholesalerId: "w-cotton",
    wholesalerName: "코튼클럽",
    categorySlug: "tops",
    colors: ["화이트", "블랙", "그레이", "소라", "핑크"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    priceMin: 4500,
    priceMax: 5200,
    status: "ON_SALE",
    purchased: true,
    favorited: true,
    listedAt: "2026-08-22",
    favoritedAt: "2026-08-27",
  },
  {
    id: "p-highwaist-denim",
    name: "하이웨스트 데님 팬츠",
    code: "SU-15",
    wholesalerId: "w-denim",
    wholesalerName: "데님하우스",
    categorySlug: "bottoms",
    colors: ["연청", "진청"],
    sizes: ["S", "M", "L"],
    priceMin: 18000,
    priceMax: 19000,
    status: "ON_SALE",
    purchased: false,
    favorited: false,
    listedAt: "2026-08-21",
    favoritedAt: null,
  },
  {
    id: "p-pleats-skirt",
    name: "플리츠 스커트",
    code: "SU-11",
    wholesalerId: "w-moodon",
    wholesalerName: "무드온",
    categorySlug: "bottoms",
    colors: ["블랙", "베이지"],
    sizes: ["S", "M", "L", "XL"],
    priceMin: 7500,
    priceMax: 8200,
    status: "ON_SALE",
    purchased: false,
    favorited: true,
    listedAt: "2026-08-20",
    favoritedAt: "2026-08-18",
  },
  {
    id: "p-linen-blouse",
    name: "여름 린넨 블라우스",
    code: "SU-51",
    wholesalerId: "w-moodon",
    wholesalerName: "무드온",
    categorySlug: "tops",
    colors: ["화이트", "소라"],
    sizes: ["S", "M", "L", "XL"],
    priceMin: 16000,
    priceMax: 17000,
    status: "ON_SALE",
    purchased: false,
    favorited: false,
    listedAt: "2026-08-30",
    favoritedAt: null,
  },
  {
    id: "p-basic-tee",
    name: "기본 반팔 티셔츠",
    code: "SU-52",
    wholesalerId: "w-moodon",
    wholesalerName: "무드온",
    categorySlug: "tops",
    colors: ["화이트", "블랙", "그레이", "민트"],
    sizes: ["S", "M", "L", "XL"],
    priceMin: 8500,
    priceMax: 9000,
    status: "ON_SALE",
    purchased: false,
    favorited: false,
    listedAt: "2026-08-29",
    favoritedAt: null,
  },
  {
    id: "p-hood-zipup",
    name: "스트릿 후드 집업",
    code: "SU-53",
    wholesalerId: "w-moodon",
    wholesalerName: "무드온",
    categorySlug: "outer",
    colors: ["블랙", "차콜", "그레이"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    priceMin: 28000,
    priceMax: 29500,
    status: "ON_SALE",
    purchased: false,
    favorited: false,
    listedAt: "2026-08-27",
    favoritedAt: null,
  },
  {
    id: "p-daily-slacks",
    name: "데일리 슬랙스",
    code: "SU-54",
    wholesalerId: "w-moodon",
    wholesalerName: "무드온",
    categorySlug: "bottoms",
    colors: ["블랙", "차콜"],
    sizes: ["S", "M", "L", "XL"],
    priceMin: 19000,
    priceMax: 20000,
    status: "ON_SALE",
    purchased: false,
    favorited: false,
    listedAt: "2026-08-26",
    favoritedAt: null,
  },
  {
    id: "p-fleece-wide",
    name: "기모 와이드 팬츠",
    code: "SU-62",
    wholesalerId: "w-moodon",
    wholesalerName: "무드온",
    categorySlug: "bottoms",
    colors: ["블랙", "차콜"],
    sizes: ["S", "M", "L"],
    priceMin: 21000,
    priceMax: 22000,
    /* 시즌이 끝난 상품 — 흐린 카드로 목록에 남되 링크가 없다 */
    status: "SEASON_ENDED",
    purchased: false,
    favorited: false,
    listedAt: "2026-02-14",
    favoritedAt: null,
  },
  {
    id: "p-kids-sweat",
    name: "키즈 맨투맨",
    code: "SU-58",
    wholesalerId: "w-moodon",
    wholesalerName: "무드온",
    categorySlug: "tops",
    colors: ["아이보리", "민트", "핑크"],
    sizes: ["S", "M", "L"],
    priceMin: 11000,
    priceMax: 11800,
    status: "ON_SALE",
    purchased: false,
    favorited: false,
    listedAt: "2026-08-19",
    favoritedAt: null,
  },
  {
    id: "p-fleece-knit-dress",
    name: "기모 니트 원피스",
    code: "SU-64",
    wholesalerId: "w-lavien",
    wholesalerName: "라비앙",
    categorySlug: "dress-set",
    colors: ["차콜", "버건디"],
    sizes: ["S", "M"],
    priceMin: 23000,
    priceMax: 24000,
    status: "SEASON_ENDED",
    purchased: false,
    /* 찜해 둔 뒤 시즌이 끝난 경우. 목록에는 남고 주문만 잠긴다 */
    favorited: true,
    listedAt: "2026-01-30",
    favoritedAt: "2026-08-25",
  },
  {
    id: "p-canvas-tote",
    name: "캔버스 토트백",
    code: "SU-71",
    wholesalerId: "w-urban",
    wholesalerName: "어반무드",
    categorySlug: "bags",
    colors: ["아이보리", "블랙", "카키"],
    sizes: ["Free"],
    priceMin: 9000,
    priceMax: 9000,
    status: "ON_SALE",
    purchased: false,
    favorited: false,
    listedAt: "2026-08-18",
    favoritedAt: null,
  },
  {
    id: "p-strap-sandal",
    name: "스트랩 샌들",
    code: "SU-73",
    wholesalerId: "w-lavien",
    wholesalerName: "라비앙",
    categorySlug: "shoes",
    colors: ["블랙", "베이지"],
    sizes: ["S", "M", "L"],
    priceMin: 21000,
    priceMax: 22000,
    status: "ON_SALE",
    purchased: false,
    favorited: false,
    listedAt: "2026-08-17",
    favoritedAt: null,
  },
  {
    id: "p-leather-belt",
    name: "레더 벨트",
    code: "SU-77",
    wholesalerId: "w-urban",
    wholesalerName: "어반무드",
    categorySlug: "accessories",
    colors: ["블랙", "브라운", "골드"],
    sizes: ["Free"],
    priceMin: 6500,
    priceMax: 6500,
    status: "ON_SALE",
    purchased: false,
    favorited: false,
    listedAt: "2026-08-16",
    favoritedAt: null,
  },
  {
    id: "p-washed-denim-jacket",
    name: "워시드 데님 자켓",
    code: "SU-81",
    wholesalerId: "w-denim",
    wholesalerName: "데님하우스",
    categorySlug: "outer",
    colors: ["연청", "중청"],
    sizes: ["S", "M", "L", "XL"],
    priceMin: 32000,
    priceMax: 34000,
    status: "ON_SALE",
    purchased: false,
    favorited: false,
    listedAt: "2026-08-15",
    favoritedAt: null,
  },
];

/** 도매처 홈이 쓴다. 없는 id로 들어오면 화면이 `notFound()`로 간다 */
export function findWholesaler(id: string): Wholesaler | undefined {
  return WHOLESALERS.find((w) => w.id === id);
}

/** 그 도매처가 마켓에 올린 상품 전부 */
export function productsOfWholesaler(wholesalerId: string): CatalogProduct[] {
  return CATALOG_PRODUCTS.filter((p) => p.wholesalerId === wholesalerId);
}

/** 도매처 홈 `신상` — 최근 7일. 기준일은 더미 데이터의 가장 최근 게시일이다 */
export const NEW_ARRIVAL_SINCE = "2026-08-24";
