/**
 * 도매 서버가 내려주는 에러 코드.
 *
 * 스펙(OpenAPI)에는 안 담기는 값이라 손으로 옮긴다 — 서버는 이걸 `@Operation` 설명에만
 * 적어 둔다. 그래서 코드젠이 대신 만들어 줄 수 없고, 여기가 유일한 목록이다.
 *
 * **소매와 어휘가 다르다** — 미승인이 도매는 `NOT_APPROVED`, 소매는 `ACCOUNT_NOT_APPROVED`다.
 * 그래서 `@ondo/api`가 아니라 이 앱 안에 둔다.
 */
export const WHOLESALE_ERROR_CODE = {
  UNAUTHENTICATED: "UNAUTHENTICATED",
  NOT_APPROVED: "NOT_APPROVED",
  ACCESS_DENIED: "ACCESS_DENIED",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // 가입 — 형식이 아니라 정책을 어겼을 때. 화면에서 각각 다르게 안내해야 해서 코드가 따로 있다
  EMAIL_DUPLICATED: "EMAIL_DUPLICATED",
  BIZ_REG_NO_DUPLICATED: "BIZ_REG_NO_DUPLICATED",
  PASSWORD_POLICY_VIOLATED: "PASSWORD_POLICY_VIOLATED",
  REQUIRED_CONSENT_MISSING: "REQUIRED_CONSENT_MISSING",
  REQUIRED_DOCUMENT_MISSING: "REQUIRED_DOCUMENT_MISSING",

  // 상품·게시 — 400은 "요청이 틀렸다"(칸에 붙인다), 409는 "지금은 안 된다"(문구로 안내)
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  CATEGORY_NOT_LEAF: "CATEGORY_NOT_LEAF",
  COLOR_DUPLICATED: "COLOR_DUPLICATED",
  SIZE_DUPLICATED: "SIZE_DUPLICATED",
  OPTION_REQUIRED: "OPTION_REQUIRED",
  PRICE_REQUIRED: "PRICE_REQUIRED",
  INVARIANT_VIOLATED: "INVARIANT_VIOLATED",
  TRANSITION_NOT_ALLOWED: "TRANSITION_NOT_ALLOWED",
  VARIANT_HAS_STOCK: "VARIANT_HAS_STOCK",
  VARIANT_ALLOCATED: "VARIANT_ALLOCATED",
  VARIANT_HAS_BACKORDER: "VARIANT_HAS_BACKORDER",
  VARIANT_IN_PENDING_ORDER: "VARIANT_IN_PENDING_ORDER",

  // 주문·포장 — 400은 요청 본문이 틀린 것(라인 누락·중복·초과), 409는 지금 상태에서 안 되는 것
  ORDER_ITEM_MISSING: "ORDER_ITEM_MISSING",
  ORDER_ITEM_NOT_IN_ORDER: "ORDER_ITEM_NOT_IN_ORDER",
  DUPLICATE_ORDER_ITEM: "DUPLICATE_ORDER_ITEM",
  ALLOCATION_EXCEEDS_ORDER: "ALLOCATION_EXCEEDS_ORDER",
  ALLOCATION_EXCEEDS_REMAINING: "ALLOCATION_EXCEEDS_REMAINING",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  DOCUMENT_FROZEN: "DOCUMENT_FROZEN",

  // 미송 배분 — 400은 요청 본문(같은 미송 중복), 409는 이미 해소된 미송에 다시 배분
  DUPLICATE_BACKORDER: "DUPLICATE_BACKORDER",
  BACKORDER_NOT_OPEN: "BACKORDER_NOT_OPEN",

  // 재고 — 입고는 400(같은 SKU·같은 단가 로트 중복)·409(멱등키 재사용·상태 충돌),
  // 조정은 409(0 아래·주문처리중 아래로 내려감)
  DUPLICATE_LOT: "DUPLICATE_LOT",
  IDEMPOTENCY_KEY_REUSED: "IDEMPOTENCY_KEY_REUSED",
  STATE_CONFLICT: "STATE_CONFLICT",
  STOCK_BELOW_ZERO: "STOCK_BELOW_ZERO",
  STOCK_BELOW_ALLOCATED: "STOCK_BELOW_ALLOCATED",

  // 출고 — 포장(POST /outbounds)은 400(중복 줄·소매처 섞임·수령 방식 섞임)·409(이미 포장된 줄),
  // 확정(POST …/ship)은 409(이미 출고·빈 봉투·재고 부족)
  DUPLICATE_PACKING_ITEM: "DUPLICATE_PACKING_ITEM",
  RETAILER_MIXED: "RETAILER_MIXED",
  RECEIVE_BY_MIXED: "RECEIVE_BY_MIXED",
  PACKING_NOT_READY: "PACKING_NOT_READY",
  OUTBOUND_EMPTY: "OUTBOUND_EMPTY",

  // 정산 — 입금(POST /payments)은 400(미래 일시·같은 주문 중복·다른 소매처 주문)·409(멱등키 재사용·미확정 주문·
  // 배분이 입금액/미수를 넘음), 계좌는 400(중복·주계좌 직접 해제), 소매처 목록은 400(허용 안 된 정렬)
  PAID_AT_IN_FUTURE: "PAID_AT_IN_FUTURE",
  DUPLICATE_ORDER: "DUPLICATE_ORDER",
  ORDER_RETAILER_MISMATCH: "ORDER_RETAILER_MISMATCH",
  ORDER_NOT_CONFIRMED: "ORDER_NOT_CONFIRMED",
  ALLOCATION_EXCEEDS_PAYMENT: "ALLOCATION_EXCEEDS_PAYMENT",
  ALLOCATION_EXCEEDS_OUTSTANDING: "ALLOCATION_EXCEEDS_OUTSTANDING",
  DUPLICATE_BANK_ACCOUNT: "DUPLICATE_BANK_ACCOUNT",
  PRIMARY_ACCOUNT_CANNOT_BE_UNSET: "PRIMARY_ACCOUNT_CANNOT_BE_UNSET",
  SORT_NOT_ALLOWED: "SORT_NOT_ALLOWED",

  // 로그인 실패는 하나뿐이다 — 이메일 없음과 비밀번호 틀림을 서버가 구분해 주지 않는다(계정 열거 방지)
  LOGIN_FAILED: "LOGIN_FAILED",
} as const;

export type WholesaleErrorCode =
  (typeof WHOLESALE_ERROR_CODE)[keyof typeof WHOLESALE_ERROR_CODE];
